# Configuração básica
baseURL = "https://tratamentes.pt/"
languageCode = "pt-pt"
title = "TrataMentes | Massagem Terapêutica em Lisboa e Cascais"
theme = "manus"

# Configurações de idiomas
defaultContentLanguage = "pt"
defaultContentLanguageInSubdir = false

[languages]
  [languages.pt]
    languageName = "Português"
    weight = 1
    contentDir = "content/pt"
  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"

# Menus
[menu]
  [[menu.main]]
    identifier = "inicio"
    name = "Início"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "sobre"
    name = "Sobre"
    url = "/sobre/"
    weight = 2
  [[menu.main]]
    identifier = "servicos"
    name = "Serviços"
    url = "/servicos/"
    weight = 3
  [[menu.main]]
    identifier = "localizacoes"
    name = "Localizações"
    url = "/localizacoes/"
    weight = 4
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 5
  [[menu.main]]
    identifier = "galeria"
    name = "Galeria"
    url = "/galeria/"
    weight = 6
  [[menu.main]]
    identifier = "contacto"
    name = "Contacto"
    url = "/contacto/"
    weight = 7

# Parâmetros personalizados
[params]
  description = "Massagem terapêutica profissional em Lisboa e Cascais. Mais de 20 anos de experiência no alívio de dores e tensões."
  author = "João Goulart"
  # Redes sociais
  instagram = "https://instagram.com/trata.mentes"
  facebook = "https://facebook.com/trata.mentes"
  linkedin = "https://linkedin.com/in/zendomus"
  # Informações de contacto
  email = "contato@tratamentes.pt"
  phone = "+351 937 543 312"
  # Localizações
  [params.locations]
    [params.locations.lisboa1]
      name = "Lisboa (Braamcamp) "
      address = "Rua Braamcamp 88, 3º Esq, 1250-050 Lisboa"
    [params.locations.lisboa2]
      name = "Lisboa (Alvalade)"
      address = "Rua Jorge Colaço 32A, 1700-253 Lisboa"
    [params.locations.cascais]
      name = "Cascais (Clinica Now)"
      address = "Av. Eng. Adelino Amaro da Costa 599 A, 2750-279 Cascais"
